CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

DROP TABLE IF EXISTS worker_heartbeats CASCADE;
DROP TABLE IF EXISTS ledger_audit_events CASCADE;
DROP TABLE IF EXISTS ledger_entries CASCADE;
DROP TABLE IF EXISTS transfer_requests CASCADE;
DROP TABLE IF EXISTS account_balances CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

CREATE TABLE tenants (
  tenant_id integer PRIMARY KEY,
  tenant_name text NOT NULL,
  risk_tier text NOT NULL CHECK (risk_tier IN ('standard','enhanced','restricted')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE accounts (
  account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(tenant_id),
  external_account_ref text NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('checking','savings','wallet','merchant_settlement')),
  currency char(3) NOT NULL DEFAULT 'USD',
  status text NOT NULL CHECK (status IN ('active','frozen','closed')),
  opened_at timestamptz NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (tenant_id, external_account_ref)
);

CREATE TABLE account_balances (
  account_id bigint PRIMARY KEY REFERENCES accounts(account_id),
  tenant_id integer NOT NULL REFERENCES tenants(tenant_id),
  currency char(3) NOT NULL DEFAULT 'USD',
  available_balance numeric(18,2) NOT NULL,
  pending_balance numeric(18,2) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (available_balance > -1000000),
  CHECK (pending_balance > -1000000)
);

CREATE TABLE transfer_requests (
  transfer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(tenant_id),
  from_account_id bigint NOT NULL REFERENCES accounts(account_id),
  to_account_id bigint NOT NULL REFERENCES accounts(account_id),
  amount numeric(18,2) NOT NULL CHECK (amount > 0),
  currency char(3) NOT NULL DEFAULT 'USD',
  status text NOT NULL CHECK (status IN ('pending','posted','failed','cancelled')),
  idempotency_key text NOT NULL UNIQUE,
  requested_at timestamptz NOT NULL DEFAULT now(),
  posted_at timestamptz,
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (from_account_id <> to_account_id)
);

CREATE TABLE ledger_entries (
  ledger_entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(tenant_id),
  transfer_id bigint REFERENCES transfer_requests(transfer_id),
  account_id bigint NOT NULL REFERENCES accounts(account_id),
  posted_at timestamptz NOT NULL,
  direction text NOT NULL CHECK (direction IN ('debit','credit')),
  amount numeric(18,2) NOT NULL CHECK (amount > 0),
  currency char(3) NOT NULL DEFAULT 'USD',
  status text NOT NULL CHECK (status IN ('posted','reversed','void')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE ledger_audit_events (
  audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(tenant_id),
  transfer_id bigint REFERENCES transfer_requests(transfer_id),
  event_type text NOT NULL,
  event_at timestamptz NOT NULL DEFAULT now(),
  actor text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE worker_heartbeats (
  worker_name text PRIMARY KEY,
  tenant_id integer REFERENCES tenants(tenant_id),
  last_seen_at timestamptz NOT NULL,
  current_transfer_id bigint,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX accounts_tenant_status_idx ON accounts(tenant_id, status);
CREATE INDEX account_balances_tenant_idx ON account_balances(tenant_id);
CREATE INDEX transfer_requests_tenant_status_idx ON transfer_requests(tenant_id, status, requested_at);
CREATE INDEX transfer_requests_from_idx ON transfer_requests(from_account_id);
CREATE INDEX transfer_requests_to_idx ON transfer_requests(to_account_id);
CREATE INDEX ledger_entries_account_idx ON ledger_entries(account_id);
CREATE INDEX ledger_entries_transfer_idx ON ledger_entries(transfer_id);
CREATE INDEX ledger_entries_tenant_posted_idx ON ledger_entries(tenant_id, posted_at);
CREATE INDEX ledger_audit_transfer_idx ON ledger_audit_events(transfer_id);

-- A posted transfer must have at most one debit and at most one credit ledger row.
-- The posting function below inserts both rows atomically in the same transaction, so
-- these indexes prevent duplicate ledger legs during retry/concurrency scenarios while
-- still allowing non-transfer historical ledger rows with transfer_id IS NULL.
CREATE UNIQUE INDEX ledger_entries_one_debit_per_transfer_idx
  ON ledger_entries(transfer_id)
  WHERE transfer_id IS NOT NULL AND direction = 'debit';

CREATE UNIQUE INDEX ledger_entries_one_credit_per_transfer_idx
  ON ledger_entries(transfer_id)
  WHERE transfer_id IS NOT NULL AND direction = 'credit';

INSERT INTO tenants (tenant_id, tenant_name, risk_tier, created_at)
SELECT g, 'Tenant ' || g,
       CASE WHEN g % 11 = 0 THEN 'restricted' WHEN g % 5 = 0 THEN 'enhanced' ELSE 'standard' END,
       now() - (g * interval '9 days')
FROM generate_series(1, 24) AS g;

INSERT INTO accounts (tenant_id, external_account_ref, account_type, currency, status, opened_at, metadata)
SELECT t.tenant_id,
       'acct-' || t.tenant_id || '-' || lpad(a::text, 5, '0'),
       CASE WHEN a % 17 = 0 THEN 'merchant_settlement' WHEN a % 5 = 0 THEN 'wallet' WHEN a % 3 = 0 THEN 'savings' ELSE 'checking' END,
       'USD',
       CASE WHEN a % 97 = 0 THEN 'frozen' ELSE 'active' END,
       now() - ((a + t.tenant_id) * interval '13 hours'),
       jsonb_build_object('segment', CASE WHEN a % 10 = 0 THEN 'business' ELSE 'consumer' END, 'region', CASE WHEN t.tenant_id % 3 = 0 THEN 'west' WHEN t.tenant_id % 3 = 1 THEN 'east' ELSE 'central' END)
FROM tenants t
CROSS JOIN generate_series(1, 120) AS a;

INSERT INTO account_balances (account_id, tenant_id, currency, available_balance, pending_balance, updated_at)
SELECT account_id,
       tenant_id,
       currency,
       (10000 + ((account_id % 900) * 13.37))::numeric(18,2),
       ((account_id % 7) * 5.00)::numeric(18,2),
       now() - ((account_id % 48) * interval '1 hour')
FROM accounts;

INSERT INTO transfer_requests (tenant_id, from_account_id, to_account_id, amount, currency, status, idempotency_key, requested_at, posted_at, metadata)
SELECT a1.tenant_id,
       a1.account_id,
       a2.account_id,
       (10 + (g % 250) * 1.11)::numeric(18,2),
       'USD',
       CASE WHEN g % 9 = 0 THEN 'pending' ELSE 'posted' END,
       'seed-' || g,
       now() - ((g % 10000) * interval '90 seconds'),
       CASE WHEN g % 9 = 0 THEN NULL ELSE now() - ((g % 10000) * interval '90 seconds') + interval '12 seconds' END,
       jsonb_build_object('channel', CASE WHEN g % 4 = 0 THEN 'ach' WHEN g % 4 = 1 THEN 'card' WHEN g % 4 = 2 THEN 'wallet' ELSE 'internal' END, 'batch', g % 37)
FROM generate_series(1, 5000) AS g
JOIN accounts a1 ON a1.account_id = ((g % 2880) + 1)
JOIN accounts a2 ON a2.account_id = (((g + 23) % 2880) + 1)
WHERE a1.tenant_id = a2.tenant_id
  AND a1.account_id <> a2.account_id;

INSERT INTO ledger_entries (tenant_id, transfer_id, account_id, posted_at, direction, amount, currency, status, metadata)
SELECT a.tenant_id,
       NULL,
       a.account_id,
       now() - ((g % 120) * interval '1 day') - ((a.account_id % 86400) * interval '1 second'),
       CASE WHEN (g + a.account_id) % 2 = 0 THEN 'debit' ELSE 'credit' END,
       (1 + ((g * 17 + a.account_id) % 1000) / 10.0)::numeric(18,2),
       'USD',
       'posted',
       jsonb_build_object('source', CASE WHEN g % 5 = 0 THEN 'reconciliation' ELSE 'card_network' END, 'merchant_category', CASE WHEN g % 6 = 0 THEN 'travel' WHEN g % 6 = 1 THEN 'groceries' WHEN g % 6 = 2 THEN 'fuel' WHEN g % 6 = 3 THEN 'software' WHEN g % 6 = 4 THEN 'dining' ELSE 'other' END)
FROM accounts a
JOIN LATERAL generate_series(1, 55) AS g ON true;

INSERT INTO ledger_entries (tenant_id, transfer_id, account_id, posted_at, direction, amount, currency, status, metadata)
SELECT tr.tenant_id, tr.transfer_id, tr.from_account_id, tr.posted_at, 'debit', tr.amount, tr.currency, 'posted', jsonb_build_object('source','seed_transfer')
FROM transfer_requests tr
WHERE tr.status = 'posted'
UNION ALL
SELECT tr.tenant_id, tr.transfer_id, tr.to_account_id, tr.posted_at, 'credit', tr.amount, tr.currency, 'posted', jsonb_build_object('source','seed_transfer')
FROM transfer_requests tr
WHERE tr.status = 'posted';

INSERT INTO ledger_audit_events (tenant_id, transfer_id, event_type, event_at, actor, details)
SELECT tr.tenant_id,
       tr.transfer_id,
       CASE WHEN tr.status = 'posted' THEN 'posted' ELSE 'queued' END,
       tr.requested_at,
       'seed-worker-' || (tr.tenant_id % 6),
       jsonb_build_object('status', tr.status, 'amount', tr.amount)
FROM transfer_requests tr
WHERE tr.transfer_id % 3 = 0;

INSERT INTO worker_heartbeats (worker_name, tenant_id, last_seen_at, current_transfer_id, metadata)
SELECT 'posting-worker-' || g,
       ((g - 1) % 24) + 1,
       now() - (g * interval '7 seconds'),
       NULL,
       jsonb_build_object('queue', 'ledger-posting', 'region', CASE WHEN g % 2 = 0 THEN 'primary' ELSE 'secondary' END)
FROM generate_series(1, 12) AS g;

INSERT INTO transfer_requests (transfer_id, tenant_id, from_account_id, to_account_id, amount, currency, status, idempotency_key, requested_at, metadata)
VALUES
  (900001, 1, 1, 2, 125.00, 'USD', 'pending', 'deadlock-demo-a-to-b', now(), jsonb_build_object('demo','opposite-direction')),
  (900002, 1, 2, 1, 80.00, 'USD', 'pending', 'deadlock-demo-b-to-a', now(), jsonb_build_object('demo','opposite-direction')),
  (900003, 1, 3, 4, 40.00, 'USD', 'pending', 'control-demo-c-to-d', now(), jsonb_build_object('demo','unrelated'));

UPDATE account_balances
SET available_balance = CASE WHEN account_id = 1 THEN 100000.00 WHEN account_id = 2 THEN 100000.00 ELSE available_balance END,
    pending_balance = 0,
    updated_at = now()
WHERE account_id IN (1,2);

CREATE OR REPLACE FUNCTION process_transfer(p_transfer_id bigint)
RETURNS TABLE(processed_transfer_id bigint, debit_account_id bigint, credit_account_id bigint, processed_amount numeric, final_status text)
LANGUAGE plpgsql
AS $$
DECLARE
  r transfer_requests%ROWTYPE;
  v_locked_balance_count integer;
  v_updated_balance_count integer;
  v_inserted_ledger_count integer;
  v_posted_at timestamptz;
BEGIN
  SELECT *
  INTO r
  FROM transfer_requests
  WHERE transfer_id = p_transfer_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'transfer % not found', p_transfer_id;
  END IF;

  IF r.status = 'posted' THEN
    RETURN QUERY SELECT r.transfer_id, r.from_account_id, r.to_account_id, r.amount, r.status;
    RETURN;
  END IF;

  IF r.status <> 'pending' THEN
    RAISE EXCEPTION 'transfer % is not pending', p_transfer_id;
  END IF;

  /*
    The previous workflow updated the debit balance first and the credit balance
    second. Two opposite-direction transfers for the same account pair could
    therefore acquire row locks in opposite orders and deadlock:

      transfer A: lock account 1, then wait for account 2
      transfer B: lock account 2, then wait for account 1

    Lock every balance row touched by the transfer up front, in one deterministic
    account_id order, before applying either delta. Transactions that conflict on
    the same accounts now queue behind the first account in the ordered set rather
    than forming a wait cycle. This preserves the same debit/credit semantics while
    making concurrent opposite-direction posting safe.
  */
  SELECT count(*)
  INTO v_locked_balance_count
  FROM (
    SELECT b.account_id
    FROM account_balances b
    WHERE b.tenant_id = r.tenant_id
      AND b.account_id IN (r.from_account_id, r.to_account_id)
    ORDER BY b.account_id
    FOR UPDATE
  ) AS locked_balances;

  IF v_locked_balance_count <> 2 THEN
    RAISE EXCEPTION 'expected to lock 2 balance rows for transfer %, locked %', r.transfer_id, v_locked_balance_count;
  END IF;

  v_posted_at := clock_timestamp();

  UPDATE account_balances b
  SET available_balance = b.available_balance +
        CASE
          WHEN b.account_id = r.from_account_id THEN -r.amount
          WHEN b.account_id = r.to_account_id THEN r.amount
          ELSE 0
        END,
      updated_at = v_posted_at
  WHERE b.tenant_id = r.tenant_id
    AND b.account_id IN (r.from_account_id, r.to_account_id);

  GET DIAGNOSTICS v_updated_balance_count = ROW_COUNT;
  IF v_updated_balance_count <> 2 THEN
    RAISE EXCEPTION 'expected to update 2 balance rows for transfer %, updated %', r.transfer_id, v_updated_balance_count;
  END IF;

  INSERT INTO ledger_entries (tenant_id, transfer_id, account_id, posted_at, direction, amount, currency, status, metadata)
  VALUES
    (r.tenant_id, r.transfer_id, r.from_account_id, v_posted_at, 'debit', r.amount, r.currency, 'posted', jsonb_build_object('source','posting_worker')),
    (r.tenant_id, r.transfer_id, r.to_account_id, v_posted_at, 'credit', r.amount, r.currency, 'posted', jsonb_build_object('source','posting_worker'));

  GET DIAGNOSTICS v_inserted_ledger_count = ROW_COUNT;
  IF v_inserted_ledger_count <> 2 THEN
    RAISE EXCEPTION 'expected to insert 2 ledger rows for transfer %, inserted %', r.transfer_id, v_inserted_ledger_count;
  END IF;

  INSERT INTO ledger_audit_events (tenant_id, transfer_id, event_type, actor, details)
  VALUES (r.tenant_id, r.transfer_id, 'posted', current_user, jsonb_build_object('from_account_id', r.from_account_id, 'to_account_id', r.to_account_id));

  UPDATE transfer_requests
  SET status = 'posted',
      posted_at = v_posted_at,
      failure_reason = NULL
  WHERE transfer_id = r.transfer_id;

  RETURN QUERY SELECT r.transfer_id, r.from_account_id, r.to_account_id, r.amount, 'posted'::text;
END;
$$;

CREATE OR REPLACE FUNCTION reset_deadlock_demo()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM ledger_audit_events WHERE transfer_id IN (900001, 900002, 900003);
  DELETE FROM ledger_entries WHERE transfer_id IN (900001, 900002, 900003);
  UPDATE transfer_requests
  SET status = 'pending', posted_at = NULL, failure_reason = NULL, requested_at = now()
  WHERE transfer_id IN (900001, 900002, 900003);
  UPDATE account_balances
  SET available_balance = CASE WHEN account_id IN (1,2) THEN 100000.00 WHEN account_id IN (3,4) THEN 50000.00 ELSE available_balance END,
      pending_balance = 0,
      updated_at = now()
  WHERE account_id IN (1,2,3,4);
END;
$$;

ANALYZE;

